# Generated by Django 5.1.4 on 2025-01-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_tg_chat_id_user_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chat_id',
            new_name='tg_chat_id',
        ),
    ]
